config/routes.rb
AutosparesApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :adts , only: [:create, :destroy, :edit]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root 'static_pages#home'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'

  match '/add',  to: 'adts#edit',            via: 'get'

 

end

app/views/layouts/_footer.html.erb
<!--подвал сайта -->
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Помощь", help_path %></li>
      <li><%= link_to "О проекте", about_path%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- шапка сайта-->
<header class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<!-- ссылка на сайт -->
			<%= link_to "Кулинарикс", root_path, id: "logo"%>
			<!-- навигация -->
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Главная", root_path%></li>

					<!-- меню в зависимости от авторизации пользователя -->
					<% if signed_in? %>
                  <li><%= link_to "Создать объявление", add_path %></li>
            			<li><%= link_to "Сообщество", users_path %></li>
            			<li id="fat-menu" class="dropdown" >
              				<a class="dropdown-toggle" data-toggle="dropdown">Профиль<span class="caret"></span>
              				</a> 
              				<ul class="dropdown-menu" role="menu">
               					<li><%= link_to "Аккаунт", current_user %></li>
                				<li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                				<li class="divider"></li>
                				<li><%= link_to "Выход", signout_path, method: "delete" %>
                				</li>
              				</ul>
            			</li>

          			<% else %>
            			<li><%= link_to "Зарегистрироваться или войти", signin_path %></li>
          			<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <!--шаблон title-->
	  <title><%= full_title(yield(:title)) %></title>
	  <!-- включение каскадных таблиц стиля -->
	   <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!-- если IE -->
    <%= render 'layouts/shim' %>
	</head>

	<body>
		<!--Шапка сайта -->
		<%= render 'layouts/header' %>

		<!-- контент страниц, оценка -->
		<div class="container">
     		 <% flash.each do |key, value| %>
        		<div class="alert alert-<%= key %>"><%= value %></div>
      		 <% end %>
      	<%= yield %>
		<!-- подвал сайта -->
		<%= render 'layouts/footer' %>
		<!-- отладочная информация
		<%= debug(params) if Rails.env.development? %>-->
		</div>
	</body>
</html>